[params.profileMode]
  enabled = true
  title = "Hi, Iâ€™m Nishant ðŸ‘‹"
  subtitle = "Site Reliability / DevOps Engineer | Kubernetes | Cloud | Automation"

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

  [[params.profileMode.buttons]]
    name = "About"
    url = "/about/"
